@startuml Constructorabler
class Constructorable 

Constructorable *--> "*" TypeParameter : genericParameter 
Constructorable *--> "*" Annotation : modAnnotations 
Constructorable *--> "*" AccessModifier : accessModifiers
Constructorable *--> "*" ParameterSeqLike : parameterSeqs

hide class circle
hide class methods

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

@enduml 