@startuml
class Definable {
    identifier:String
}

Definable --> "*" Annotation : annotations 
Definable --> "*" Modifier : modifiers

hide class circle
hide class methods

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

@enduml 