@startuml
class Defines 

Defines *--> "*" ValDef : vals 
Defines *--> "*" DefDef : defs 
Defines *--> "*" VarDef : vars
Defines *--> "*" TypeDef : types
Defines *--> "*" Class : classes
Defines *--> "*" Enum  : enums 
Defines *--> "*" Object : objects 
Defines *--> "*" Given : givens 

hide class circle
hide class methods

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

@enduml 