@startuml Defs
class DefDef {
    \n
    \n
    \n
    \n
}

class ValDef {
}

class VarDef {
}

note right of TypeParameter : isCovariant = false && \nisContravariant = false
Defineable <|-- DefDef 
DefDef *--down> "*" TypeParameter : genericParameter
DefDef *--right> "*" ParameterSeqLike : parameterSeqs
DefDef *--left> "*" Parameter : implicits
DefDef *--down> "      0..1" Type : returnType

"Defineable " <|-- ValDef 
ValDef --> "0..1" "Type " : type 

"Defineable  " <|-- VarDef 
VarDef --> "0..1" "Type  " : type 

hide class circle
hide class methods
hide Defineable members
hide "Defineable " members
hide "Defineable  " members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

skinparam note {
    BackgroundColor White
    BorderColor Red
}
@enduml 