@startuml

class Extension 

Extension --left> "*" TypeParameter : genericParameters
Extension *--> "1" Parameter : parameter
Extension --> "0..*  " UsingParameterSeq : usingParameters
Extension *--right> "1..*" DefDef : extensionMethods

hide class circle
hide class methods

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}
@enduml