@startuml Defines 
class Defines {
    \n
    \n
    \n 
}

Defines *--left> "*" ValDef : vals 
Defines *--left> "*" DefDef : "\n defs" 
Defines *--> "*" VarDef : vars
Defines *--> "*" TypeDef : types
Defines *--> "*" Class : classes
Defines *--> "*" Enum  : enums 
Defines *--right> "*\n" Object : "\nobjects" 
Defines *--right> "*" Given : givens 

hide class circle
hide class methods

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

@enduml 