@startuml Class
class Class extends Defineable, Constructerable, Defines {
    isCaseClass : Boolean 
    isTrait : Boolean 
    isSuperTrait : Boolean 
}

Class --> "*" Class : innerClasses\n {refines classes}
Class --> "*" Import : imports
Class --> "*" Export : exports 
Class *--left> "0..1  " Inherit : inherits
Class *--> "*" Extension : "extensions"
Class *--> "*" ClassParameterSeqLike : parameterSeqs \n{refines parameterSeqs}
Class *--left> "*" ClassParameter : \nimplicits

hide class circle
hide class methods
hide Defineable members
hide Constructerable members 
hide Defines members 

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}
@enduml