@startuml
class UMLElement 


UMLElement <|-- TopLevelElement 
UMLElement <|-- StereotypeElement
UMLElement <|-- ClassBodyElement 
UMLElement <|-- PackageBodyElement 
UMLElement <|-- CompartementElement
PackageBodyElement <|-- Package 
TopLevelElement <|-- Package
TopLevelElement <|-- Relationship
TopLevelElement <|-- Class 
PackageBodyElement <|-- Class 
StereotypeElement <|-- Class 
StereotypeElement <|-- Parameter 
StereotypeElement <|-- Operation
ClassBodyElement <|-- Operation 
CompartementElement <|-- Operation 
TopLevelElement <|-- CompartedClass
PackageBodyElement <|-- CompartedClass
TopLevelElement <|-- Note 
StereotypeElement <|-- Note 
PackageBodyElement <|-- Note 
Note <|-- DirectionNote
Note <|-- AliasNote 
Note <|-- LinkNote 
TopLevelElement <|-- SkinParam 
TopLevelElement <|-- Hide 
PackageBodyElement <|-- Relationship
StereotypeElement <|-- Relationship
StereotypeElement <|-- Attribute
CompartementElement <|-- Attribute 
ClassBodyElement <|-- Attribute 

hide class circle
hide class methods 
hide enum methods 


skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}
@enduml 