@startuml
class UMLElement 
class Class {
}

class Relationship {
    
}

UMLElement <|-- Relateable 
UMLElement <|-- TopLevelable
UMLElement <|-- Operation 
UMLElement <|-- Parameter 
TopLevelable <|-- Relationship
Relateable <|-- Class 
TopLevelable <|-- Class 

hide class circle
hide class methods 
hide enum methods 


skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}
@enduml 