@startuml "Two classes"
class Class1 << case class >> {
    
}
class BaseTrait << trait >> {
    s : String
    foo(s : String) : String
}
Class1 --|> BaseTrait : " "
skinparam ClassBackgroundcolor White
skinparam ClassArrowColor Black
skinparam ClassBorderColor Black
hide class circle
@enduml