@startuml
class Class {
    identifier : String 
}

Class --> "*" Class : innerClasses
Class --> "*" Annotation : annotation
Class --> "0..1  " AccessModifier : packageAccess
Class --> "*" Import : imports
Class --> "*" Export : exports
Class *--up> "*" ValDef : vals
Class *--up> "*" VarDef : vars 
Class *--up> "*" DefDef : defs  
Class *--up> "*" TypeDef : types  
Class *--> "*" ParameterSeq : classParams
Class *--left> "0..1  " Inherit : "inherits"
Class *--up> "*" Extension : "extensions"

hide class circle
hide class methods

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}



@enduml