@startuml

class CompilationUnit {
    package : String [0..1]
}
class TopLevel extends Defines {
    \n
    \n 
    \n 
}
class Package {
    identifier : String 
}

CompilationUnit *--> "1" TopLevel : topLevelDefinitions 
TopLevel *--> "*" Import : imports  
TopLevel *--> "*" Export : exports
TopLevel *--> "*" Extension : extensions 
TopLevel *--> "*\n\n" Object : packageObjects
TopLevel *---> "*" Package : innerPackages 
Package ---> "1" TopLevel : packageDefs

note left of Object : isPackageObject = true

hide class circle
hide class methods
hide Defines members 

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

skinparam note {
    BackgroundColor White 
    BorderColor Red 
}
@enduml 